# Enhanced Dependabot configuration for SplitWiser
# Monitors multiple package ecosystems for security and version updates
# Documentation: https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Python dependencies (Backend - Root level)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    assignees:
      - "devasy23"
    reviewers:
      - "devasy23"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "python"
      - "backend"

  # Python dependencies (Backend directory)
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    assignees:
      - "devasy23"
    reviewers:
      - "devasy23"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "python"
      - "backend"

  # Node.js dependencies (Frontend)
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
    assignees:
      - "vrajpatelll"
    reviewers:
      - "vrajpatelll"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "javascript"
      - "frontend"
    # Group React Native and Expo related updates
    groups:
      react-native:
        patterns:
          - "react-native*"
          - "react"
          - "react-dom"
          - "@react-*"
      expo:
        patterns:
          - "expo*"
          - "@expo/*"
      navigation:
        patterns:
          - "@react-navigation/*"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "09:00"
    assignees:
      - "devasy23"
    reviewers:
      - "devasy23"
    commit-message:
      prefix: "ci"
      include: "scope"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "github-actions"
      - "ci/cd"
