[phases.setup]
nixPkgs = ["python312", "pip"]

# Use the default Python install behavior but ensure we use the right requirements file
[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "echo 'Build phase: Copying backend files'",
    "cp -r backend/* . || echo 'Backend files already in place'"
]

[start]
# Run directly from the root directory since we copied the files there
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT"

[variables]
PYTHONPATH = "/app"
PYTHONUNBUFFERED = "1"

# Let Nixpacks handle virtual environment creation automatically
[nixpacks]
