name: Bundle Analysis

on:
  pull_request:
    paths:
      - 'frontend/**'
    branches: [ main, master ]
  push:
    paths:
      - 'frontend/**'
    branches: [ main, master ]

jobs:
  bundle-analysis:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    
    - name: Install Dependencies
      run: |
        cd frontend
        npm ci
    
    - name: Build for Bundle Analysis
      run: |
        cd frontend
        # Use Expo's export command for bundle analysis (Metro bundler)
        npx expo export --platform web --output-dir web-build
    
    - name: Analyze Bundle Size
      run: |
        cd frontend
        # Install Metro bundle analyzer and bc for calculations
        npm install --no-save @expo/metro-config metro-visualizer
        sudo apt-get update && sudo apt-get install -y bc
        
        # Generate bundle report using Metro
        echo "📊 Analyzing bundle size for Expo/React Native project..."
        
        # Check if web-build directory exists
        if [ -d "web-build" ]; then
          echo "✅ Web build directory found"
          ls -la web-build/
          
          # Calculate bundle sizes
          if [ -d "web-build/static/js" ]; then
            echo "📁 JavaScript bundle files:"
            find web-build/static/js -name "*.js" -type f -exec ls -lh {} \; | awk '{print $5 " " $9}'
            
            # Calculate total bundle size
            TOTAL_SIZE=$(find web-build/static/js -name "*.js" -type f -exec stat -c%s {} \; | awk '{sum+=$1} END {print sum}')
            TOTAL_SIZE_MB=$(echo "scale=2; $TOTAL_SIZE / 1024 / 1024" | bc -l)
            echo "📊 Total JavaScript bundle size: ${TOTAL_SIZE_MB} MB"
            
            # Create a simple analysis report
            echo "# Bundle Analysis Report" > bundle-analysis.md
            echo "" >> bundle-analysis.md
            echo "## Bundle Size Summary" >> bundle-analysis.md
            echo "- Total JavaScript bundle size: **${TOTAL_SIZE_MB} MB**" >> bundle-analysis.md
            echo "" >> bundle-analysis.md
            echo "## Individual Files" >> bundle-analysis.md
            find web-build/static/js -name "*.js" -type f -exec ls -lh {} \; | awk '{print "- " $9 ": " $5}' >> bundle-analysis.md
            
            cat bundle-analysis.md
          else
            echo "❌ No JavaScript bundles found in web-build/static/js"
          fi
        else
          echo "❌ No web-build directory found after export"
          echo "📁 Available directories:"
          ls -la
        fi
    
    - name: Upload Bundle Analysis Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: bundle-analysis-report
        path: frontend/bundle-analysis.md
        retention-days: 30
    
    - name: Upload Bundle Analysis to Codecov
      uses: codecov/codecov-action@v4
      if: github.actor != 'dependabot[bot]' && hashFiles('frontend/bundle-analysis.md') != ''
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: bundle,frontend,javascript
        name: "Bundle Analysis"
        fail_ci_if_error: false
    
    - name: Bundle Analysis Skipped
      if: github.actor == 'dependabot[bot]'
      run: echo "📦 Bundle analysis skipped for Dependabot PR"
