name: Run Tests

on:
  pull_request:
    branches: [ main, master, feature/*]
  push:
    branches: [ main, master ]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd backend
        pip install -r requirements.txt
        
    - name: Run tests
      run: |
        cd $GITHUB_WORKSPACE
        export PYTHONPATH=$GITHUB_WORKSPACE:$GITHUB_WORKSPACE/backend
        pytest --cov=./backend --cov-report=xml:coverage.xml backend/tests/

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.xml
        fail_ci_if_error: false
      # Skip codecov upload for Dependabot PRs since they don't have access to secrets
      if: github.actor != 'dependabot[bot]'
      
    - name: Codecov upload skipped for Dependabot
      if: github.actor == 'dependabot[bot]'
      run: echo "📊 Codecov upload skipped for Dependabot PR - tests still run and pass!"
